### ISSUE TITLE
Issue importing Variant Groups

### ISSUE THREAD

**Issue by holly-curata** [Agence-DnD/PIMGento#48] opened 2015-08-04 22:00 UTC
NOTE: CLIENT IMPLEMENTATION

Hi there,
I’m using Akeneo 1.3.18 and Pimgento connector 1.2.3 and Magento 1.9.1. I’m also now exporting products from Akeneo using the Akeneo Enhanced Connector.

The issue I’m having is related to the import/creation of configurable products in Magento from variant groups. Each time I run the product import, the URL of the configurable product changes and creates a redirect in Magento. This is leading to dynamic URL’s and a massive number of redirects that grows each time I run a product import.

**Comment by hbrandl** [comment] 2015-08-20 11:21
Hi @holly-curata,

I'm having the same problem.

Here's what I've come up with so far:

The configurable product seems to be partially created. You can access it by manually crafting the url. Go to the catalog page where you see the configurable product, note down the id (e.g. 210).
Now go to catalog -> manage products and click on any product. This should bring you to a url like this one
> /index.php/admin/admin/catalog_product/edit/id/200/key/1234567randomhash890/
now change the id in the url to the id of the configurable product e.g.
> index.php/admin/admin/catalog_product/edit/id/210/key/1234567randomhash890/

In my case I see a value for price and sku set as well as visibiltiy set to catalog and search.
Once I click 'save' something is fixed in the database and I can see it in the catalog -> manage products view.

I'm now going to investigate which database entries are missing and why not all attributes are filled.

**Comment by hbrandl** [comment] 2015-08-20 12:45
The reason why the configurable product is not shown in the 'manage products' view is that the attribute 96 / status is not set for configurable products (it's not set for lots of other attributes too).
This is happening in the table catalog_product_entity_int.

Next question seems to be, why are all those attributes not set.

**Comment by magentix** [comment] 2015-09-01 15:18
Yes, the problem is than "status" attribute for configurable product is not setted on import. In Pimgento Configuration, set "enabled > 1" for "Default configurable attributes values" option (System > Configuration > Pimgento > Product)

(Note: "enabled" attribute must be exported in product CSV file).

**Closed by magentix** 2015-09-01 15:18 UTC
